### ISSUE TITLE
PrismaInitializationException: in docker container only

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [odroe/prisma-dart#233]
Hello, I am creating simple jwt auth project with dart_frog and prisma (postgresql). Right now I am trying to push all of that into docker container. The thing is that prisma locally works just fine however in container I constantly receive an error and don't know how to fix it. 

`PrismaInitializationException: Cannot find the query engine binary (Basename: query-engine-darwin-arm64)`

**docker-compose.yml**
```
version: "3.8"

services:

  api:
    restart: always
    build: ./
    ports:
      - 8080:8080
    environment:
      JWT_ISSUER: my_company_name
      JWT_ACCESS_SECRET: here-goes-your-access-secret
      JWT_REFRESH_SECRET: here-goes-your-refresh-secret
      DATABASE_URL: postgresql://postgres:12345678@db:5432/jwt_auth?schema=public

  db:
    restart: always
    image: postgres:15.3
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678

volumes:
  db_data:
```

**Dockerfile**
```
# An example of using a custom Dockerfile with Dart Frog
# Official Dart image: https://hub.docker.com/_/dart
# Specify the Dart SDK base image version using dart:<version> (ex: dart:2.17)
FROM dart:stable AS build

WORKDIR /app

# Copy Dependencies
COPY packages/db ./packages/db

# Install Dependencies
RUN dart pub get -C packages/db

# Resolve app dependencies.
COPY pubspec.* ./
RUN dart pub get

# Copy app source code and AOT compile it.
COPY . .

# Generate a production build.
RUN dart pub global activate dart_frog_cli
RUN dart pub global run dart_frog_cli:dart_frog build

ARG JWT_ISSUER
ARG JWT_ACCESS_SECRET
ARG JWT_REFRESH_SECRET
ARG DATABASE_URL
# Ensure packages are still up-to-date if anything has changed.
RUN dart pub get --offline
RUN dart compile exe --define=JWT_ISSUER=${JWT_ISSUER} --define=JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET} --define=JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET} --define=DATABASE_URL=${DATABASE_URL} build/bin/server.dart -o build/bin/server

# Build minimal serving image from AOT-compiled `/server` and required system
# libraries and configuration files stored in `/runtime/` from the build stage.
FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/build/bin/server /app/bin/
# Uncomment the following line if you are serving static files.
# COPY --from=build /app/build/public /public/

# Start the server.
CMD ["/app/bin/server"]
```

**docker-compose up --build output**
```
jwt_auth-api-1  | ERROR - 2023-06-09 17:32:22.792658
jwt_auth-api-1  | GET /api/v1/user
jwt_auth-api-1  | Error thrown by handler.
jwt_auth-api-1  | PrismaInitializationException: Cannot find the query engine binary (Basename: query-engine-darwin-arm64)
jwt_auth-api-1  | package:orm/binary_engine.dart 79                        BinaryEngine.resolvedExecutable
jwt_auth-api-1  | package:orm/binary_engine.dart 178                       BinaryEngine._createProcess
jwt_auth-api-1  | package:orm/binary_engine.dart 148                       BinaryEngine.start
jwt_auth-api-1  | package:orm/universal_engine.dart 59                     UniversalEngine.request
jwt_auth-api-1  | package:orm/src/client/model_delegate.dart 40            ModelDelegate._execute
jwt_auth-api-1  | package:orm/src/client/model_delegate.dart 29            ModelDelegate.$query
jwt_auth-api-1  | package:db/src/generated/prisma/prisma_client.dart 1244  UserModelDelegateExtension.findUnique.<fn>
jwt_auth-api-1  | package:orm/src/client/prisma_fluent.dart 37             PrismaFluent.queryBuilder.<fn>
jwt_auth-api-1  | package:db/src/generated/prisma/prisma_client.dart 1253  UserModelDelegateExtension.findUnique
jwt_auth-api-1  | app/build/routes/api/v1/user/index.dart 14               onRequest
jwt_auth-api-1  | app/build/bin/server.dart 51                             buildApiV1UserHandler.<fn>
jwt_auth-api-1  | package:dart_frog/src/router.dart 364                    RouterEntry.invoke.<fn>
jwt_auth-api-1  | package:dart_frog/src/router.dart 372                    RouterEntry.invoke
jwt_auth-api-1  | package:dart_frog/src/router.dart 165                    Router.call
jwt_auth-api-1  | package:dart_frog/src/provider.dart 8                    provider.<fn>.<fn>
jwt_auth-api-1  | package:dart_frog/src/provider.dart 8                    provider.<fn>.<fn>
jwt_auth-api-1  | package:dart_frog/src/provider.dart 8                    provider.<fn>.<fn>
jwt_auth-api-1  | app/build/bin/server.dart 36                             buildRootHandler.<fn>
jwt_auth-api-1  | dart:core                                                Function.apply
jwt_auth-api-1  | package:dart_frog/src/router.dart 148                    Router._invokeMountedHandler
jwt_auth-api-1  | package:dart_frog/src/router.dart 105                    Router.mount.<fn>
jwt_auth-api-1  | package:dart_frog/src/router.dart 359                    RouterEntry.invoke.<fn>
jwt_auth-api-1  | package:dart_frog/src/router.dart 372                    RouterEntry.invoke
jwt_auth-api-1  | package:dart_frog/src/router.dart 165                    Router.call
jwt_auth-api-1  | package:dart_frog/src/shelf_adapters.dart 43             toShelfHandler.<fn>
jwt_auth-api-1  | package:shelf/src/cascade.dart 75                        Cascade.handler.<fn>
jwt_auth-api-1  | package:dart_frog/src/shelf_adapters.dart 34             fromShelfHandler.<fn>
jwt_auth-api-1  | package:dart_frog/src/serve.dart 22                      serve.<fn>
jwt_auth-api-1  | 
```
