### ISSUE TITLE
.env not work

### ISSUE THREAD

**Issue by jacobaraujo7** [odroe/prisma-dart#65]
Version 2.4.4-dev.0

**Comment by Quatton** [comment]
Come here to add on this.

In `.env`, I have

```env
DATABASE_URL="postgresql://postgres:[PASSWORD]@db.[SUPABASE_PROJECT_ID].supabase.co:5432/postgres"
```

But when I ran `flutter run orm db pull`, the console output
```
Exception: An error happened. Check the data field for details.
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:7
   |
 6 |   provider          = "postgresql"
 7 |   url               = env("DATABASE_URL")
   |
```

This is my `pubspec.yaml`
```yml
dependencies:
  flutter:
    sdk: flutter

  # Other dependencies
  # ...

  flutter_dotenv: ^5.0.2
  orm: ^2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
```

Tried directly inserting the URL into `schema.prisma` and it worked just fine (but this is not ideal.)
```prisma

generator client {
  provider = "prisma-client-dart"
}

datasource db {
  provider          = "postgresql"
  url               = "postgresql://postgres:[PASSWORD]@db.[SUPABASE_PROJECT_ID].supabase.co:5432/postgres"
}

// Conveniently generated this model from Supabase
model users {
  id String    @unique @db.Uuid
  created_at   DateTime? @default(now()) @db.Timestamptz(6)
}
```
